apiVersion: v1
kind: Service
metadata:
  name: sprint-poc-cloud
  labels:
    app: cloud-app
    project: sprint-poc
spec:
  type: NodePort
  ports:
  - port: 8080
    name: ui
  selector:
    app: cloud-app
    project: sprint-poc
