def label = "mypod-${UUID.randomUUID().toString()}"
podTemplate(label: label,
	containers: [
	  containerTemplate(name: 'maven', image: 'maven:3.3.9-jdk-8-alpine', ttyEnabled: true, command: 'cat'),
	  containerTemplate(name: 'docker', image: 'docker:stable', ttyEnabled: true, command: 'cat'),
	  containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.8.0', command: 'cat', ttyEnabled: true)
	],
	volumes: [hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')]
	) {
	
	node(label) {
		
	  
	  stage('Get Source') {
	  	git "https://github.com/deepthisprint/cloud-poc-app.git"
	  }

	 // def props = readProperties  file:'deployment/pipeline.properties'
	  def tag = "1.0.0"
	  def gitSrc = "https://github.com/deepthisprint/cloud-poc-app.git"
	  def dockerRegistry = "https://mycluster.icp:8500"
	  def image = "mycluster.icp:8500/sprint-poc/cloud-poc"
	  def deployment = "deployment/cloud-poc-deployment.yaml"
	  def config = "deployment/cloud-poc-configmap.yaml"
	  def service ="deployment/cloud-poc-service.yaml"
	  def selector = "app=cloud-app,project=sprint-poc"
	  def namespace = "deepthi"
	  def jar = "target/spring-jms-activemq-helloworld-0.0.1-SNAPSHOT.jar"


	  stage('Build Maven project') {
		container('maven') {
			sh "mvn -B -DskipTests clean package"
		}
	  }
	  stage('Build Docker image') {
		container('docker') {
		  docker.withRegistry("${dockerRegistry}", 'icp-id') {
			sh "docker build --build-arg JAR_FILE=${jar} -t ${image}:${tag} ."
			sh "docker push ${image}:${tag}"
			sh "docker tag ${image}:${tag} ${image}:latest"
			sh "docker push ${image}:latest"
		  }
		}
	  }
	  
	  stage( 'Deploy to Cluster' ) {
		container('kubectl') {
		  withCredentials([[$class: 'UsernamePasswordMultiBinding',
							  credentialsId: 'icp-id',
							  usernameVariable: 'DOCKER_HUB_USER',
							  passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
			  sh "kubectl delete deployments -n ${namespace} --selector=${selector}"
			  sh "sleep 20"
			  sh "kubectl apply -n ${namespace} -f ${config} -f ${deployment}"
			  sh "sleep 20"
			  sh "kubectl apply -n ${namespace} -f ${service}"
		  }
		}
	  }
	}
  }
